services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050" # Para producción
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
