services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_IGNORE_WARNINGS: true
    volumes:
      - /app/node_modules
    command: >
      npm start