services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    environment:
      NODE_ENV: production
      NODE_OPTIONS: --no-warnings
      NEXT_PUBLIC_IGNORE_WARNINGS: true
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npm start || true"
