services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
      - "8080:8080"
    environment:
      NODE_ENV: production
      NODE_OPTIONS: --no-warnings
      NEXT_PUBLIC_IGNORE_WARNINGS: true
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "if [ -d .next ]; then npm start; else next dev -p 8050; fi"